### ISSUE TITLE
Update Notification within app [enhancment]

### ISSUE THREAD

**Issue by PuppySlvt** [z0w13/pkstatus#41]
Would be nice to have a notification when there is a new update

**Comment by PuppySlvt** [comment]
![image_2024-04-11_011845338](https://github.com/z0w13/pkstatus/assets/166667116/37e60598-1c2b-4659-a7fb-4dc817c1d4bd)

**Comment by z0w13** [comment]
Added in a1d6d7a fixed in 4ebf979
